### ISSUE TITLE
Plot displaying multiple points per x-axis value

### ISSUE THREAD

**Issue by clarabicalho** [DeclareDesign/DDWizard#103]
In some designs, the number of parameters to vary is greater than the number of aesthetic options. In those cases, we end up with a plot with multiple values for the same x-axis value. Thanks to @macartan for pointing out there should be better behavior for this. Suggestions:

* Add a drop down menu along with plot config parameters to limit plotting to certain values (not already included in aesthetic options).
* Set all plot aesthetics to any available varying arguments

**Comment by internaut** [comment]
Will fix this with displaying a warning see #219.
