### ISSUE TITLE
Diagnostic table when not varying parameters

### ISSUE THREAD

**Issue by clarabicalho** [DeclareDesign/DDWizard#149]
Say you are interested in using DDWizard as an interface to interact with a single design (i.e., export the diagnosis table of said design).

Currently app returns errors and disables both plot and table in diagnosis tab. Shouldn't users still be able to see the diagnostic table for that single design? I.e., return error and disable plot, but enable diagnosis table output and download?

**Comment by internaut** [comment]
Implemented this (don't remember the issue number).
