### ISSUE TITLE
Set title

### ISSUE THREAD

**Issue by internaut** [DeclareDesign/DDWizard#215]
Looks like the app doesn't have a <title> tag yet, hence the URL is displayed as title instead.

**Comment by zerinahuang** [comment]
Yes, I didn't set the title, because I didn't know the font from declare design website. You can consider the logo of declare design as title.

**Comment by internaut** [comment]
No, I mean the HTML site's <title>, which is then shown in the browser window title.

**Comment by internaut** [comment]
Closed by latest commit.
